version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mbg"
  - package-ecosystem: "docker-compose"
    directories:
      - "/docker-compose.*.yaml"
    schedule:
      interval: "daily"
    assignees:
      - "mbg"
