name: network-wait
version: 0.2.0.0
github: "mbg/network-wait"
license: MIT
author: "Michael B. Gale"
maintainer: "github@michael-gale.co.uk"
copyright: "2022 Michael B. Gale"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Lightweight library for waiting on networked services to become available.
category: Network

description: Please see the README on GitHub at <https://github.com/mbg/network-wait#readme>

dependencies:
  - base >= 4.7 && < 5
  - exceptions
  - network
  - retry

flags:
  postgres:
    description: Enable Postgres support.
    manual: true
    default: false
  redis:
    description: Enable Redis support.
    manual: true
    default: false

when:
  - condition: flag(postgres)
    dependencies:
      - postgresql-simple
  - condition: flag(redis)
    dependencies:
      - hedis

ghc-options:
  - -Wall

library:
  source-dirs: src
  when:
    - condition: flag(postgres)
      exposed-modules: Network.Wait.PostgreSQL
    - condition: flag(redis)
      exposed-modules: Network.Wait.Redis

tests:
  network-wait-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - network-wait
      - network-simple
      - tasty
      - tasty-hunit
  network-wait-test-postgres:
    main: Spec.hs
    source-dirs: test-postgres
    dependencies:
      - network-wait
      - tasty
      - tasty-hunit
    when:
      condition: flag(postgres)
      then:
        buildable: true
      else:
        buildable: false
  network-wait-test-redis:
    main: Spec.hs
    source-dirs: test-redis
    dependencies:
      - network-wait
      - tasty
      - tasty-hunit
    when:
      condition: flag(redis)
      then:
        buildable: true
      else:
        buildable: false
